# Generated by Django 5.0.1 on 2024-02-08 18:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique_for_month=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('gait_speed', models.FloatField(blank=True, null=True)),
                ('grip_dom', models.FloatField(blank=True, null=True)),
                ('grip_ndom', models.FloatField(blank=True, null=True)),
                ('FI_ADL', models.FloatField(blank=True, null=True)),
                ('FI_IADL', models.FloatField(blank=True, null=True)),
                ('chair', models.FloatField(blank=True, null=True)),
                ('leg_raise', models.FloatField(blank=True, null=True)),
                ('full_tandem', models.FloatField(blank=True, null=True)),
                ('srh', models.IntegerField(blank=True, null=True)),
                ('eye', models.IntegerField(blank=True, null=True)),
                ('hear', models.IntegerField(blank=True, null=True)),
                ('func', models.IntegerField(blank=True, null=True)),
                ('dias', models.FloatField(blank=True, null=True)),
                ('sys', models.FloatField(blank=True, null=True)),
                ('pulse', models.FloatField(blank=True, null=True)),
                ('trig', models.FloatField(blank=True, null=True)),
                ('crp', models.FloatField(blank=True, null=True)),
                ('hdl', models.FloatField(blank=True, null=True)),
                ('ldl', models.FloatField(blank=True, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('igf1', models.FloatField(blank=True, null=True)),
                ('hgb', models.FloatField(blank=True, null=True)),
                ('fib', models.FloatField(blank=True, null=True)),
                ('fer', models.FloatField(blank=True, null=True)),
                ('chol', models.FloatField(blank=True, null=True)),
                ('wbc', models.FloatField(blank=True, null=True)),
                ('mch', models.FloatField(blank=True, null=True)),
                ('hba1c', models.FloatField(blank=True, null=True)),
                ('vitd', models.FloatField(blank=True, null=True)),
                ('BP_med', models.IntegerField(blank=True, null=True)),
                ('anticoagulant_med', models.IntegerField(blank=True, null=True)),
                ('chol_med', models.IntegerField(blank=True, null=True)),
                ('hipknee_treat', models.IntegerField(blank=True, null=True)),
                ('lungasthma_med', models.IntegerField(blank=True, null=True)),
                ('longill', models.IntegerField(blank=True, null=True)),
                ('limitact', models.IntegerField(blank=True, null=True)),
                ('effort', models.IntegerField(blank=True, null=True)),
                ('smkevr', models.IntegerField(blank=True, null=True)),
                ('smknow', models.IntegerField(blank=True, null=True)),
                ('mobility', models.IntegerField(blank=True, null=True)),
                ('country', models.IntegerField(blank=True, null=True)),
                ('alcohol', models.IntegerField(blank=True, null=True)),
                ('jointrep', models.IntegerField(blank=True, null=True)),
                ('fractures', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('ethnicity', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
