# Generated by Django 5.0.1 on 2024-02-08 22:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthModel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='BP_med',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='anticoagulant_med',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='chol_med',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='effort',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='fractures',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='height',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='hipknee_treat',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='jointrep',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='limitact',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='longill',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='lungasthma_med',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='mobility',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='smkevr',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='smknow',
        ),
        migrations.CreateModel(
            name='BackgroundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique_for_month=True)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('BP_med', models.IntegerField(blank=True, null=True)),
                ('anticoagulant_med', models.IntegerField(blank=True, null=True)),
                ('chol_med', models.IntegerField(blank=True, null=True)),
                ('hipknee_treat', models.IntegerField(blank=True, null=True)),
                ('lungasthma_med', models.IntegerField(blank=True, null=True)),
                ('longill', models.IntegerField(blank=True, null=True)),
                ('limitact', models.IntegerField(blank=True, null=True)),
                ('effort', models.IntegerField(blank=True, null=True)),
                ('smkevr', models.IntegerField(blank=True, null=True)),
                ('smknow', models.IntegerField(blank=True, null=True)),
                ('mobility', models.IntegerField(blank=True, null=True)),
                ('country', models.IntegerField(blank=True, null=True)),
                ('alcohol', models.IntegerField(blank=True, null=True)),
                ('jointrep', models.IntegerField(blank=True, null=True)),
                ('fractures', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('ethnicity', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='healthdata',
            name='background',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='healthModel.backgrounddata'),
            preserve_default=False,
        ),
    ]
