# Generated by Django 5.0.1 on 2024-02-08 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthModel', '0002_remove_healthdata_bp_med_remove_healthdata_alcohol_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgrounddata',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='healthdata',
            old_name='userId',
            new_name='user',
        ),
    ]
