# Generated by Django 5.0.1 on 2024-02-15 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthModel', '0004_alter_backgrounddata_date_alter_healthdata_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_question', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_id', models.CharField(max_length=20)),
                ('response', models.FloatField()),
                ('type', models.CharField(max_length=12)),
                ('save_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthModel.savedata')),
            ],
        ),
    ]
