# Generated by Django 4.2.10 on 2024-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthModel', '0005_savedata_savedresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='srh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedata',
            name='last_question',
            field=models.IntegerField(default=0),
        ),
    ]
