# Generated by Django 5.0.1 on 2024-02-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthModel', '0006_alter_healthdata_srh_alter_savedata_last_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='eye',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='func',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='hear',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
