import { ProfileSurveyQuestion } from "../types/Profile";

// need to change for production
export const API_URL = "http://146.190.125.251:8000/api";

export const surveyQuestions: Array<ProfileSurveyQuestion> = [
  {
    variableId: "gait_speed",
    prettyName: "Gait Speed",
    question: "gait speed averaged between two timed walks",
    hasQuantitative: true,
    unit: "m/s",
    qualitativeOptions: [
      "unable",
      "extremely slow",
      "slow",
      "average",
      "fast",
      "extremely fast",
    ],
    required: false,
    mean: 0.853874057544418,
    stdev: 0.28451581955254013,
  },
  {
    variableId: "grip_dom",
    prettyName: "Dominant Hand Grip Strength",
    question: "your grip strength of your dominant hand",
    hasQuantitative: true,
    unit: "lbs",
    qualitativeOptions: [
      "Very weak",
      "Weak",
      "Average",
      "Strong",
      "Very strong",
    ],
    required: false,
    mean: 28.436364178481274,
    stdev: 11.308967992782993,
  },
  {
    variableId: "grip_ndom",
    prettyName: "Non-Dominant Hand Grip Strength",
    question: "your grip strength of your non-dominant hand",
    hasQuantitative: true,
    unit: "lbs",
    qualitativeOptions: [
      "Very weak",
      "Weak",
      "Average",
      "Strong",
      "Very strong",
    ],
    required: false,
    mean: 26.07880308937994,
    stdev: 10.5158958288211,
  },
  {
    variableId: "FI_ADL",
    prettyName: "ADL Score",
    question:
      "Any difficulty in the last 3 months because of physical, mental, emotional, or memory problems: (a) dressing (including putting on shoes and socks), (b) eating (such as cutting up your food), (c) using the toilet (including getting up and down), (d) bathing and showering, (e) getting in and out of bed, and (f) walking across a room",
    hasQuantitative: false,
    unit: "sum",
    qualitativeOptions: ["1", "2", "3", "4", "5", "6"],
    required: false,
    mean: 0.20268848442975199,
    stdev: 0.26173694862441804,
  },
  {
    variableId: "FI_IADL",
    prettyName: "IADL Score",
    question:
      "Any difficulty in the last 3 months because of physical, mental, emotional, or memory problems: (a) preparing a hot meal, (b) shopping for groceries, (c) making telephone calls, (d) taking medications, and (e) managing your money, such as paying your bills and keeping track of expenses",
    hasQuantitative: false,
    unit: "sum",
    qualitativeOptions: ["1", "2", "3", "4", "5"],
    required: false,
    mean: 0.06808106625950425,
    stdev: 0.1567108755355969,
  },
  {
    variableId: "chair",
    prettyName: "Chair Raises",
    question:
      "'I want you to try to stand up from a firm straight-backed chair, like a dining chair. First, fold your arms across your chest and sit so that your feet are on the floor; then stand up keeping your arms folded across your chest. repeat 5 times",
    hasQuantitative: true,
    unit: "sec",
    qualitativeOptions: [
      "extremely slow",
      "slow",
      "average",
      "fast",
      "extremely fast",
    ],
    required: false,
    mean: 11.535945600583949,
    stdev: 4.220377324322096,
  },
  {
    variableId: "leg_raise",
    prettyName: "Leg Raise",
    question:
      "Try to stand on one leg, whichever one you want, and raise the other leg off the ground a few inches. Stand for as long as you can - I will stop you at 30 seconds. You may use your arms, bend your knees, or move your body to maintain your balance, but try not to move your feet. Try to hold this position until I tell you to stop. You may support yourself on a chair, table or wall while getting into position.",
    hasQuantitative: true,
    unit: "sec",
    qualitativeOptions: [
      "less than half duration",
      "more than half duration",
      "full duration",
    ],
    required: false,
    mean: 2.2808316018437944,
    stdev: 0.8216907575280872,
  },
  {
    variableId: "full_tandem",
    prettyName: "Full Tandem Stance",
    question:
      "Tandem stance: stand side by side with their feet together: Ages 50-69 were asked to hold for 30 seconds, 70+ for 10 seconds. Stopwatch was stopped when the participant steps out of position or grabs the nurses arm.",
    hasQuantitative: true,
    unit: "sec",
    qualitativeOptions: [
      "less than half duration",
      "more than half duration",
      "full duration",
    ],
    required: false,
    mean: 2.070456640118188,
    stdev: 0.7301471469371483,
  },
  {
    variableId: "srh",
    prettyName: "Self-Rated Health",
    question: "How would you say your health is?",
    hasQuantitative: false,
    unit: "sec",
    qualitativeOptions: ["excellent", "very good", "good", "fair", "poor"],
    required: false,
    mean: 0.4033145172962802,
    stdev: 0.27757305612048716,
  },
  {
    variableId: "eye",
    prettyName: "Self-Rated Eyesight",
    question: "How would you rate your eyesight?",
    hasQuantitative: false,
    unit: "sec",
    qualitativeOptions: [
      "excellent",
      "very good",
      "good",
      "fair",
      "poor",
      "registered/legally blind",
    ],
    required: false,
    mean: 0.31634668892617235,
    stdev: 0.20057904741917865,
  },
  {
    variableId: "hear",
    prettyName: "Self-Rated Hearing",
    question: "How would you rate your hearing?",
    hasQuantitative: false,
    unit: "sec",
    qualitativeOptions: ["excellent", "very good", "good", "fair", "poor"],
    required: false,
    mean: 0.4104753227242377,
    stdev: 0.2797723245182508,
  },
  {
    variableId: "func",
    prettyName: "Difficulty Walking",
    question:
      "By yourself and without using any special equipment, how much difficulty do you have walking for a quarter of a mile?",
    hasQuantitative: false,
    unit: "sec",
    qualitativeOptions: [
      "no difficulty",
      "some difficulty",
      "much difficulty",
      "unable",
    ],
    required: false,
    mean: 0.1959890102227365,
    stdev: 0.3391606567006017,
  },
  {
    variableId: "dias",
    prettyName: "Diastolic Blood Pressure",
    question: "diastolic blood pressure from 3 measurements",
    hasQuantitative: true,
    unit: "mmHg",
    qualitativeOptions: [
      "extremely low",
      "low",
      "average",
      "high",
      "extremely high",
    ],
    required: false,
    mean: 75.76050022511951,
    stdev: 12.704728759608257,
  },
  {
    variableId: "sys",
    prettyName: "Systolic Blood Pressure",
    question: "systolic blood pressure from 3 measurements",
    hasQuantitative: true,
    unit: "mmHg",
    qualitativeOptions: [
      "extremely low",
      "low",
      "average",
      "high",
      "extremely high",
    ],
    required: false,
    mean: 137.76928908123554,
    stdev: 20.270871864472632,
  },
  {
    variableId: "pulse",
    prettyName: "Pulse",
    question: "pulse",
    hasQuantitative: true,
    unit: "bpm",
    qualitativeOptions: [
      "extremely low",
      "low",
      "average",
      "high",
      "extremely high",
    ],
    required: false,
    mean: 68.42104803653973,
    stdev: 11.285062475935565,
  },
  {
    variableId: "trig",
    prettyName: "Blood Triglyceride Level",
    question:
      "Together with total and HDL cholesterol, they provide a lipid profile that can give information on the risk of cardiovascular disease.",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: [
      "Normal: Less than 150 mg/dL (1.69 mmol/L)",
      "Borderline high: 150 to 199 mg/dL (1.69 to 2.25 mmol/L)",
      "High: 200 to 499 mg/dL (2.26 to 5.64 mmol/L)",
      "Very high: 500 mg/dL or above (5.65 mmol/L)",
    ],
    required: false,
    mean: 0.37934330777806136,
    stdev: 0.5011242623973755,
  },
  {
    variableId: "crp",
    prettyName: "Blood CRP Level",
    question:
      "The level of this protein in the blood gives information on inflammatory activity in the body, and it is also associated with risk of heart disease.",
    hasQuantitative: true,
    unit: "mg/l",
    qualitativeOptions: [
      "Normal: Less than 0.3 mg/dL",
      "Minor elevation: 0.3 to 1.0 mg/dL",
      "Moderate elevation: 1.0 to 10.0 mg/d",
      "Marked elevation: More than 10.0 mg/dL",
      "Severe elevation: More than 50.0 mg/dL",
    ],
    required: false,
    mean: 0.6397056535068669,
    stdev: 1.1353660719205658,
  },
  {
    variableId: "hdl",
    prettyName: "Blood HDL Level",
    question:
      "This is ‘good’ cholesterol, which is protective for heart disease. Triglycerides - Together with total and HDL cholesterol, they provide a lipid profile that can give information on the risk of cardiovascular disease.",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: [
      "Excellent: 60 mg/dL (1.5 mmol/L) or higher",
      "Average: 40-59 mg/dL (1-1.5 mmol/L)",
      "Low: less than 40 mg/dL (1.03 mmol/L)",
    ],
    required: false,
    mean: 1.5468664148351616,
    stdev: 0.44133941424915846,
  },
  {
    variableId: "ldl",
    prettyName: "Blood LDL Level",
    question:
      "This is ‘bad’ cholesterol; increased levels are associated with atherosclerosis, and thus myocardial infarctions, strokes and peripheral vascular disease.",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: [
      "Very High: 190 mg/dL (4.9 mmol/L) or high with coronary artery disease",
      "High: 160-189 mg/dL (3.4 - 4.9 mmol/L) or  borderline high or near optimal with coronary artery disease",
      "Near Optimal: 100 -129 mg/dL (2.6-3.3 mmol/L) or optimal with coronary artery disease",
      "Optimal: Below 100 mg/dL (Below 2.6 mmol/L)",
      "Best: Below 70 mg/dL (Below 1.8 mmol/L)",
    ],
    required: false,
    mean: 3.300098459399978,
    stdev: 1.0527448115035516,
  },
  {
    variableId: "glucose",
    prettyName: "Blood Glucose Level",
    question:
      "Blood glucose levels indicate the presence or risk of type 2 diabetes, which is associated with an increased risk of heart disease.",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: [
      "Normal Fasting blood sugar level: 100 mg/dL (5.6 mmol/L)",
      "High: 160-189 mg/dL (3.4 - 4.9 mmol/L) or  borderline high or near optimal with coronary artery disease",
      "Near Optimal: 100 -129 mg/dL (2.6-3.3 mmol/L) or optimal with coronary artery disease",
      "Optimal: Below 100 mg/dL (Below 2.6 mmol/L)",
      "Best: Below 70 mg/dL (Below 1.8 mmol/L)",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "age",
    prettyName: "Age",
    question: "How old are you?",
    hasQuantitative: true,
    unit: "years",
    qualitativeOptions: [],
    required: true,
    mean: 50,
    stdev: 15,
  },
  {
    variableId: "igf1",
    prettyName: "Insulin-Like Growth Factor",
    question:
      "These are hormones that help control reactions to stress and regulate various body processesincluding digestion, the immune system, mood, and energy usage.",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: [
      "Lower",
      "Normal: 182 to 780 ng/mL for ages 16 to 24 114 to 492 ng/mL for ages 25 to 39 90 to 360 ng/mL for ages 40 to 54",
      "Higher",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "hgb",
    prettyName: "Blood Hemoglobin Level",
    question:
      "These are measures of iron levels in the body and are related to diet and other factors",
    hasQuantitative: true,
    unit: "g/dl",
    qualitativeOptions: [
      "Lower",
      "Normal: Male: 13.8 to 17.2 grams per deciliter (g/dL) Female: 12.1 to 15.1 (g/dL)",
      "Higher",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "fib",
    prettyName: "Blood Fibrinogen Level",
    question:
      "A protein necessary for blood clotting. High levels are also associated with a higher risk of heart disease.",
    hasQuantitative: true,
    unit: "g/l",
    qualitativeOptions: [
      "Lower",
      "Normal: Between 200 and 400 mg/dL ",
      "Higher",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "fer",
    prettyName: "Blood Ferritin Level",
    question:
      "These are measures of iron levels in the body and are related to diet and other factors.",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: [
      "Lower",
      "Normal: (Male) 12 to 300 ng/mL, (Female) 12 to 150 ng/mL",
      "Higher",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "chol",
    prettyName: "Blood Total Cholesterol Level",
    question:
      "Cholesterol is a type of fat present in the blood, related to diet. Too much cholesterol in the blood increases the risk of heart disease.",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: [
      "Normal:  less than 200 mg/dL (5.17 mmol/L)",
      "Borderline high: 200 to 239 mg/dL (5.17 to 6.18 mmol/L)",
      "High:  240 mg/dL (6.21 mmol/L) or greater",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "wbc",
    prettyName: "White Blood Cell Count",
    question:
      "When looked in combination with ferritin and hemoglobin can indicate anemia.",
    hasQuantitative: true,
    unit: "billions/l",
    qualitativeOptions: ["Lower", "Normal: 4.5 to 11.0 billion/L", "Higher"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "mch",
    prettyName: "Blood Mean Corpuscular Hemoglobin Level",
    question:
      "When looked in combination with ferritin and hemoglobin can indicate anemia.",
    hasQuantitative: true,
    unit: "pg/cell",
    qualitativeOptions: [
      "Lower",
      "Normal: 320 to 360 grams per liter (g/L)",
      "Higher",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "hba1c",
    prettyName: "Blood Glycated Hemoglobin Level",
    question:
      "Indicate the presence or risk of type 2 diabetes, which is associated with an increased risk of heart disease.",
    hasQuantitative: true,
    unit: "%",
    qualitativeOptions: [
      "Normal: Less than 5.7%",
      "Prediabetes: 5.7% to 6.4%",
      "Diabetes: 6.5% or higher",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "vitd",
    prettyName: "Vitamin D Level",
    question:
      "Obtained from the diet and from sunshine, Vitamin D is needed for healthy bones.",
    hasQuantitative: true,
    unit: "nmol/L",
    qualitativeOptions: [
      "Deficiency: less than 30 nmol/L (12 ng/mL)",
      "Potential deficiency: between 30 nmol/L (12 ng/mL) and 50 nmol/L (20 ng/mL)",
      "Normal levels: between 50 nmol/L (20 ng/mL) and 125 nmol/L (50 ng/mL)",
      "High: higher than 125 nmol/L (50 ng/mL)",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "BP med",
    prettyName: "Blood Pressure Medication",
    question: "Are you taking medication for blood pressure?",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "anticoagulent med",
    prettyName: "Anticoagulent Medication",
    question: "Are you taking an anticoagulant medication, such as warfarin?",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "chol med",
    prettyName: "Cholesterol Medication",
    question:
      "Are you taking medicine to lower cholesterol / prevent cholesterol from getting high?",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "hip/knee treat",
    prettyName: "Hip/Knee Treatment",
    question:
      "Do you take medication or calcium/vitamin D pills for osteoporosis?",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "lung/asthma med",
    prettyName: "Lung/Asthma Medication",
    question:
      "Are you taking meditation for a lung condition / to prevent the return of a lung condition?",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "longill",
    prettyName: "Long Illness",
    question: "Do you have any long-standing illness, disability or infirmity?",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "limitact",
    prettyName: "Limit Activity",
    question:
      "Does any illness or disability limit your activities in any way?",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "effort",
    prettyName: "Effort Level",
    question:
      "Much of the time during the past week, have you felt that everything you did was an effort?",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "smkevr",
    prettyName: "Smoking",
    question: "Have you ever smoked cigarettes?",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "smknow",
    prettyName: "Current Smoking",
    question: "Do you smoke cigarettes at all nowadays?",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "mobility",
    prettyName: "Mobility",
    question:
      "Blood glucose levels indicate the presence or risk of type 2 diabetes, which is associated with an increased risk of heart disease.",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: [
      "1.Observed walking without help of another person or using suport",
      "2. Observed walking with help of another person or using support",
      "3. not observed - in wheelchair",
      "4. not observed - bed bound",
      "5. not observed - uncertain if respondent has impairment",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "country",
    prettyName: "Country",
    question:
      "ELSA Country of birth collapsed into UK and elsewhere to avoid disclosure",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: ["1.UK", "2. outside UK"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "alcohol",
    prettyName: "Alcohol Consumption",
    question: "In the past 12 months have you taken an alcoholic drink?",
    hasQuantitative: false,
    unit: "mmol/l",
    qualitativeOptions: [
      "1. twice a day or more",
      "2. daily or almost daily",
      "3. once or twice a week",
      "4. once or twice a month",
      "5. special occasions only",
      "6.not at all",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "jointrep",
    prettyName: "Joint Replacement",
    question: "Have you ever had any joint replacements?",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "fractures",
    prettyName: "Hip Fractures",
    question: "Have you ever fractured your hip?",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "height",
    prettyName: "Height",
    question: "What is your height?",
    hasQuantitative: true,
    unit: "cm",
    qualitativeOptions: [
      "Very Short: (Male) Less than 160cm, (Female) Less than 150cm",
      "Short: (Male) 160-179cm, (Female) 150-160cm",
      "Average: (Male) 171-180cm, (Female) 161-170cm",
      "Tall: (Male) 181-190cm, (Female) 171-180cm",
      "Very Tall: (Male) More than 191cm, (Female) More than 181cm",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "bmi",
    prettyName: "Blood Glucose Level",
    question:
      "Blood glucose levels indicate the presence or risk of type 2 diabetes, which is associated with an increased risk of heart disease.",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: [
      "Normal Fasting blood sugar level: 100 mg/dL (5.6 mmol/L)",
      "High: 160-189 mg/dL (3.4 - 4.9 mmol/L) or  borderline high or near optimal with coronary artery disease",
      "Near Optimal: 100 -129 mg/dL (2.6-3.3 mmol/L) or optimal with coronary artery disease",
      "Optimal: Below 100 mg/dL (Below 2.6 mmol/L)",
      "Best: Below 70 mg/dL (Below 1.8 mmol/L)",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "ethnicity",
    prettyName: "Ethnicity",
    question:
      "ELSA ethnic group collapsed into White and Non-white to avoid disclosure",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: ["1. White", "2. Non-White"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "sex",
    prettyName: "Sex",
    question:
      "Blood glucose levels indicate the presence or risk of type 2 diabetes, which is associated with an increased risk of heart disease.",
    hasQuantitative: true,
    unit: "mmol/l",
    qualitativeOptions: ["1. male", "2. female"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
] as const;

export const PRED_DT = 0.5;

export const graphDomains = [5, 10, 20, 50];
