# Generated by Django 5.0.1 on 2024-02-01 23:14

from django.db import migrations


def set_user_emails(apps, schema_editor):
    User = apps.get_model('users', 'User')  # Replace with your app name and User model name
    for user in User.objects.all():
        if not user.email:
            user.email = f"{user.username}@email.com"
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_email'),  # Replace with your app name and the previous migration
    ]

    operations = [
        migrations.RunPython(set_user_emails),
    ]
